name: Cataclysm Android build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "build-data/osx/**"
      - "docs/**"
      - "doxygen_doc/**"
      - "gfx/**"
      - "lang/**"
      - "lgtm/**"
      - "tools/**"
      - "!tools/format/**"
      - "utilities/**"
      - "scripts/**"
      - "**.md"
      - "**.mdx"

# We only care about the latest revision of a PR, so cancel previous instances.
concurrency:
  group: android-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_catatclysm:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 11 (android)
        uses: actions/setup-java@v4.1.0
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Set up GCC 15
        uses: egor-tensin/setup-gcc@v2
        with: { version: 15, platform: x64 }

      - name: Setup build and dependencies
        run: |
          sudo apt-get -o Acquire::Retries=3 update
          sudo apt-get -o Acquire::Retries=3 install gettext libsqlite3-dev zlib1g-dev
          g++ --version

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: android-pr-${{ github.ref_name }}
          restore-keys: |
            android-pr-${{ github.ref_name }}
            android-pr-main
            android-pr-
          max-size: 500M
          verbose: 2
          save: ${{ github.event_name != 'pull_request' }}

      - name: Build
        working-directory: ./android
        env:
          NDK_CCACHE: ccache
        run: |
          chmod +x gradlew
          ./gradlew -Pj=$((`nproc`+0)) -Pabi_arm_32=false assembleExperimentalRelease
